# Generated by Django 5.1.6 on 2026-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursestore', '0002_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='image_url',
        ),
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colleges/'),
        ),
    ]
